//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VJ.SAPGUIScript.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VJ.SAPGUIScript.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the button, for ex:&quot;wnd[1]/tbar[0]/btn[0]&quot;.
        /// </summary>
        public static string Button_Click_ControlID_Description {
            get {
                return ResourceManager.GetString("Button_Click_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string Button_Click_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("Button_Click_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a button using ID.
        /// </summary>
        public static string Button_Click_Description {
            get {
                return ResourceManager.GetString("Button_Click_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button_Click.
        /// </summary>
        public static string Button_Click_DisplayName {
            get {
                return ResourceManager.GetString("Button_Click_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of checkbox. ex:wnd[0]/usr/boxpersonas_40/chkpersonas_46.
        /// </summary>
        public static string CheckBox_ClickByID_ControlID_Description {
            get {
                return ResourceManager.GetString("CheckBox_ClickByID_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string CheckBox_ClickByID_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("CheckBox_ClickByID_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the check box based on value true / false.
        /// </summary>
        public static string CheckBox_ClickByID_Description {
            get {
                return ResourceManager.GetString("CheckBox_ClickByID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox_ClickByID.
        /// </summary>
        public static string CheckBox_ClickByID_DisplayName {
            get {
                return ResourceManager.GetString("CheckBox_ClickByID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it needs to be ticked then True, If not False.
        /// </summary>
        public static string CheckBox_ClickByID_Tick_Description {
            get {
                return ResourceManager.GetString("CheckBox_ClickByID_Tick_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick.
        /// </summary>
        public static string CheckBox_ClickByID_Tick_DisplayName {
            get {
                return ResourceManager.GetString("CheckBox_ClickByID_Tick_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;Accounting Report&quot;.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_CombMainWindowNameoBoxID_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_CombMainWindowNameoBoxID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombMainWindowNameoBoxID.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_CombMainWindowNameoBoxID_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_CombMainWindowNameoBoxID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Example: &quot;115552&quot;, Use Spy tool to find/UIpath UIExplorer.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_ComboBox_AutomationID_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_ComboBox_AutomationID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox_AutomationID.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_ComboBox_AutomationID_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_ComboBox_AutomationID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;wnd[0]/usr/subSUB1:SAPLMEGUI:6000/cmbDYN_6000-LIST&quot;.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_ComboBoxID_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_ComboBoxID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxID.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_ComboBoxID_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_ComboBoxID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Box Select item using Item Text contains.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox_SelectItem_Using_ItemTextcontains.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;Email&quot;.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_ItemText_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_ItemText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemText.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_ItemText_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_ItemText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox item text, which needs to be selected, For Ex: &quot;Email&quot;.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_SelectItemText_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_SelectItemText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectItemText.
        /// </summary>
        public static string ComboBox_SelectItem_Using_ItemTextcontains_SelectItemText_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_ItemTextcontains_SelectItemText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;wnd[0]/usr/subSUB1:SAPLMEGUI:6000/cmbDYN_6000-LIST&quot;.
        /// </summary>
        public static string ComboBox_SelectItem_Using_Key_ComboBoxID_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_Key_ComboBoxID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxID.
        /// </summary>
        public static string ComboBox_SelectItem_Using_Key_ComboBoxID_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_Key_ComboBoxID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box select item using Key.
        /// </summary>
        public static string ComboBox_SelectItem_Using_Key_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_Key_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox_SelectItem_Using_Key.
        /// </summary>
        public static string ComboBox_SelectItem_Using_Key_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_Key_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;   3&quot;, Make sure included blank as well if exists.
        /// </summary>
        public static string ComboBox_SelectItem_Using_Key_ItemKey_Description {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_Key_ItemKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemKey.
        /// </summary>
        public static string ComboBox_SelectItem_Using_Key_ItemKey_DisplayName {
            get {
                return ResourceManager.GetString("ComboBox_SelectItem_Using_Key_ItemKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;Spreadsheet...&quot;.
        /// </summary>
        public static string ContextMenuSelectItem_ContextMenuItem_Description {
            get {
                return ResourceManager.GetString("ContextMenuSelectItem_ContextMenuItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem.
        /// </summary>
        public static string ContextMenuSelectItem_ContextMenuItem_DisplayName {
            get {
                return ResourceManager.GetString("ContextMenuSelectItem_ContextMenuItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click the grid and choose the specified context menu item.
        /// </summary>
        public static string ContextMenuSelectItem_Description {
            get {
                return ResourceManager.GetString("ContextMenuSelectItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuSelectItem.
        /// </summary>
        public static string ContextMenuSelectItem_DisplayName {
            get {
                return ResourceManager.GetString("ContextMenuSelectItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;wnd[0]/usr/cntlGRID1/shellcont/shell&quot;.
        /// </summary>
        public static string ContextMenuSelectItem_GridID_Description {
            get {
                return ResourceManager.GetString("ContextMenuSelectItem_GridID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridID.
        /// </summary>
        public static string ContextMenuSelectItem_GridID_DisplayName {
            get {
                return ResourceManager.GetString("ContextMenuSelectItem_GridID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Status bar text in the sap window bottom.
        /// </summary>
        public static string Get_StatusBar_Text_Description {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_StatusBar_Text.
        /// </summary>
        public static string Get_StatusBar_Text_DisplayName {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the Status Bar Text (E/S/I....).
        /// </summary>
        public static string Get_StatusBar_Text_MessageType_Description {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_MessageType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageType.
        /// </summary>
        public static string Get_StatusBar_Text_MessageType_DisplayName {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_MessageType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of the status bar..
        /// </summary>
        public static string Get_StatusBar_Text_StatusText_Description {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_StatusText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusText.
        /// </summary>
        public static string Get_StatusBar_Text_StatusText_DisplayName {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_StatusText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Text.
        /// </summary>
        public static string Get_StatusBar_Text_StatusTextValue_Description {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_StatusTextValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusTextValue.
        /// </summary>
        public static string Get_StatusBar_Text_StatusTextValue_DisplayName {
            get {
                return ResourceManager.GetString("Get_StatusBar_Text_StatusTextValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ex:&quot;wnd[0]/usr/ctxtS_MATNR-LOW&quot;.
        /// </summary>
        public static string Get_TextBox_Value_ControlID_Description {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string Get_TextBox_Value_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Textbox value.
        /// </summary>
        public static string Get_TextBox_Value_Description {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_TextBox_Value.
        /// </summary>
        public static string Get_TextBox_Value_DisplayName {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Example:wnd[0].grdviewSA.curr[0].txtYEAR.
        /// </summary>
        public static string Get_TextBox_Value_TextboxID_Description {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_TextboxID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextboxID.
        /// </summary>
        public static string Get_TextBox_Value_TextboxID_DisplayName {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_TextboxID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the Textbox.
        /// </summary>
        public static string Get_TextBox_Value_TextBoxValue_Description {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_TextBoxValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxValue.
        /// </summary>
        public static string Get_TextBox_Value_TextBoxValue_DisplayName {
            get {
                return ResourceManager.GetString("Get_TextBox_Value_TextBoxValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the TextBox, For Ex. &quot;wnd[0]/txtINGKIL&quot;.
        /// </summary>
        public static string Get_TextEditBox_Value_ControlID_Description {
            get {
                return ResourceManager.GetString("Get_TextEditBox_Value_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string Get_TextEditBox_Value_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("Get_TextEditBox_Value_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Text Edit box value, its similar as TextBox/InputBox,, Mostly used textbox within table/grid..
        /// </summary>
        public static string Get_TextEditBox_Value_Description {
            get {
                return ResourceManager.GetString("Get_TextEditBox_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_TextEditBox_Value.
        /// </summary>
        public static string Get_TextEditBox_Value_DisplayName {
            get {
                return ResourceManager.GetString("Get_TextEditBox_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of the TextEditBox/InputBox.
        /// </summary>
        public static string Get_TextEditBox_Value_Text_Description {
            get {
                return ResourceManager.GetString("Get_TextEditBox_Value_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Get_TextEditBox_Value_Text_DisplayName {
            get {
                return ResourceManager.GetString("Get_TextEditBox_Value_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the Label For ex: &quot;wnd[0]\LBLTSKK&quot;.
        /// </summary>
        public static string GetLabelText_ControlID_Description {
            get {
                return ResourceManager.GetString("GetLabelText_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string GetLabelText_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("GetLabelText_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Text of the Label.
        /// </summary>
        public static string GetLabelText_Description {
            get {
                return ResourceManager.GetString("GetLabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLabelText.
        /// </summary>
        public static string GetLabelText_DisplayName {
            get {
                return ResourceManager.GetString("GetLabelText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Label Text.
        /// </summary>
        public static string GetLabelText_LabelText_Description {
            get {
                return ResourceManager.GetString("GetLabelText_LabelText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelText.
        /// </summary>
        public static string GetLabelText_LabelText_DisplayName {
            get {
                return ResourceManager.GetString("GetLabelText_LabelText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get SAP Status Text.
        /// </summary>
        public static string GetStatusText_Description {
            get {
                return ResourceManager.GetString("GetStatusText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStatusText.
        /// </summary>
        public static string GetStatusText_DisplayName {
            get {
                return ResourceManager.GetString("GetStatusText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of SAP Status bar .
        /// </summary>
        public static string GetStatusText_StatusText_Description {
            get {
                return ResourceManager.GetString("GetStatusText_StatusText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusText.
        /// </summary>
        public static string GetStatusText_StatusText_DisplayName {
            get {
                return ResourceManager.GetString("GetStatusText_StatusText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value of the specified cell.
        /// </summary>
        public static string Grid_GetCellValue_CellValue_Description {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_CellValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellValue.
        /// </summary>
        public static string Grid_GetCellValue_CellValue_DisplayName {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_CellValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ex:KLKJK.
        /// </summary>
        public static string Grid_GetCellValue_ColumnID_Description {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_ColumnID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnID.
        /// </summary>
        public static string Grid_GetCellValue_ColumnID_DisplayName {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_ColumnID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get grid cell value.
        /// </summary>
        public static string Grid_GetCellValue_Description {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid_GetCellValue.
        /// </summary>
        public static string Grid_GetCellValue_DisplayName {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ex:&quot;wnd[0]/usr/cntlGRID1/shellcont/shell&quot;.
        /// </summary>
        public static string Grid_GetCellValue_GridID_Description {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_GridID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridID.
        /// </summary>
        public static string Grid_GetCellValue_GridID_DisplayName {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_GridID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ex:5, Note: Rowindex starts from 0.
        /// </summary>
        public static string Grid_GetCellValue_RowIndex_Description {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_RowIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowIndex.
        /// </summary>
        public static string Grid_GetCellValue_RowIndex_DisplayName {
            get {
                return ResourceManager.GetString("Grid_GetCellValue_RowIndex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;EBELN&quot;.
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_ColumnID_Description {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_ColumnID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnID.
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_ColumnID_DisplayName {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_ColumnID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click a cell in a specified row of a Grid..
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_Description {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid_SelectCell_AndDoubleClick.
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_DisplayName {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;wnd[0]/usr/cntlGRID1/shellcont/shell&quot;.
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_GridID_Description {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_GridID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridID.
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_GridID_DisplayName {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_GridID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;6&quot;.
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_RowIndex_Description {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_RowIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowIndex.
        /// </summary>
        public static string Grid_SelectCell_AndDoubleClick_RowIndex_DisplayName {
            get {
                return ResourceManager.GetString("Grid_SelectCell_AndDoubleClick_RowIndex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click a row in a Grid.
        /// </summary>
        public static string Grid_SelectRow_AndDoubleClick_Description {
            get {
                return ResourceManager.GetString("Grid_SelectRow_AndDoubleClick_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid_SelectRow_AndDoubleClick.
        /// </summary>
        public static string Grid_SelectRow_AndDoubleClick_DisplayName {
            get {
                return ResourceManager.GetString("Grid_SelectRow_AndDoubleClick_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;wnd[0]/usr/cntlGRID1/shellcont/shell&quot;.
        /// </summary>
        public static string Grid_SelectRow_AndDoubleClick_GridID_Description {
            get {
                return ResourceManager.GetString("Grid_SelectRow_AndDoubleClick_GridID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridID.
        /// </summary>
        public static string Grid_SelectRow_AndDoubleClick_GridID_DisplayName {
            get {
                return ResourceManager.GetString("Grid_SelectRow_AndDoubleClick_GridID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;6&quot;.
        /// </summary>
        public static string Grid_SelectRow_AndDoubleClick_RowIndex_Description {
            get {
                return ResourceManager.GetString("Grid_SelectRow_AndDoubleClick_RowIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowIndex.
        /// </summary>
        public static string Grid_SelectRow_AndDoubleClick_RowIndex_DisplayName {
            get {
                return ResourceManager.GetString("Grid_SelectRow_AndDoubleClick_RowIndex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get text of a label.
        /// </summary>
        public static string Label_GetText_Description {
            get {
                return ResourceManager.GetString("Label_GetText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;Choose an Account&quot;, if no dialogbox then &quot;&quot;.
        /// </summary>
        public static string Label_GetText_DialogBox1_Description {
            get {
                return ResourceManager.GetString("Label_GetText_DialogBox1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogBox1.
        /// </summary>
        public static string Label_GetText_DialogBox1_DisplayName {
            get {
                return ResourceManager.GetString("Label_GetText_DialogBox1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;Choose an Account&quot;, if no dialogbox then &quot;&quot;.
        /// </summary>
        public static string Label_GetText_DialogBox2_Description {
            get {
                return ResourceManager.GetString("Label_GetText_DialogBox2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogBox2.
        /// </summary>
        public static string Label_GetText_DialogBox2_DisplayName {
            get {
                return ResourceManager.GetString("Label_GetText_DialogBox2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label_GetText.
        /// </summary>
        public static string Label_GetText_DisplayName {
            get {
                return ResourceManager.GetString("Label_GetText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex:&quot;wnd[0]/usr/lbl[64,3]&quot;.
        /// </summary>
        public static string Label_GetText_LabelID_Description {
            get {
                return ResourceManager.GetString("Label_GetText_LabelID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelID.
        /// </summary>
        public static string Label_GetText_LabelID_DisplayName {
            get {
                return ResourceManager.GetString("Label_GetText_LabelID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;Accouting Report&quot;.
        /// </summary>
        public static string Label_GetText_MainWindowName_Description {
            get {
                return ResourceManager.GetString("Label_GetText_MainWindowName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWindowName.
        /// </summary>
        public static string Label_GetText_MainWindowName_DisplayName {
            get {
                return ResourceManager.GetString("Label_GetText_MainWindowName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example &quot;100&quot;.
        /// </summary>
        public static string Login_Client_Description {
            get {
                return ResourceManager.GetString("Login_Client_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Login_Client_DisplayName {
            get {
                return ResourceManager.GetString("Login_Client_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login into SAP.
        /// </summary>
        public static string Login_Description {
            get {
                return ResourceManager.GetString("Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_DisplayName {
            get {
                return ResourceManager.GetString("Login_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Example: &quot;EN&quot; for english, &quot;ZH&quot; for chines and etc...,.
        /// </summary>
        public static string Login_Language_Description {
            get {
                return ResourceManager.GetString("Login_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Login_Language_DisplayName {
            get {
                return ResourceManager.GetString("Login_Language_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_Password_Description {
            get {
                return ResourceManager.GetString("Login_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password_DisplayName {
            get {
                return ResourceManager.GetString("Login_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: &quot;NRP&quot;.
        /// </summary>
        public static string Login_ServerName_Description {
            get {
                return ResourceManager.GetString("Login_ServerName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Login_ServerName_DisplayName {
            get {
                return ResourceManager.GetString("Login_ServerName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_Username_Description {
            get {
                return ResourceManager.GetString("Login_Username_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username_DisplayName {
            get {
                return ResourceManager.GetString("Login_Username_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using SSO Mode.
        /// </summary>
        public static string LoginSSO_Description {
            get {
                return ResourceManager.GetString("LoginSSO_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginSSO.
        /// </summary>
        public static string LoginSSO_DisplayName {
            get {
                return ResourceManager.GetString("LoginSSO_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the server, usually it is listed in the SAP Login Window for example: PH7 PRD.
        /// </summary>
        public static string LoginSSO_ServerName_Description {
            get {
                return ResourceManager.GetString("LoginSSO_ServerName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerName.
        /// </summary>
        public static string LoginSSO_ServerName_DisplayName {
            get {
                return ResourceManager.GetString("LoginSSO_ServerName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Main Menu based on ID.
        /// </summary>
        public static string Menu_SelectionByID_Description {
            get {
                return ResourceManager.GetString("Menu_SelectionByID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu_SelectionByID.
        /// </summary>
        public static string Menu_SelectionByID_DisplayName {
            get {
                return ResourceManager.GetString("Menu_SelectionByID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Example:&quot;wnd[0]/mbar/menu[4]/menu[8]&quot;.
        /// </summary>
        public static string Menu_SelectionByID_MenuID_Description {
            get {
                return ResourceManager.GetString("Menu_SelectionByID_MenuID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuID.
        /// </summary>
        public static string Menu_SelectionByID_MenuID_DisplayName {
            get {
                return ResourceManager.GetString("Menu_SelectionByID_MenuID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the RadioBox, for ex:&quot;wnd[1]/usr/subSUBSCREEN_STEPLOOP:SAPLSPO5:0150/sub:SAPLSPO5:0150/radSPOPLI-SELFLAG[1,0]&quot;.
        /// </summary>
        public static string RadioBox_Click_ControlID_Description {
            get {
                return ResourceManager.GetString("RadioBox_Click_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string RadioBox_Click_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("RadioBox_Click_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a radio box using ID.
        /// </summary>
        public static string RadioBox_Click_Description {
            get {
                return ResourceManager.GetString("RadioBox_Click_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioBox_Click.
        /// </summary>
        public static string RadioBox_Click_DisplayName {
            get {
                return ResourceManager.GetString("RadioBox_Click_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text/Value of the Table Cell..
        /// </summary>
        public static string Table_GetCellValue_CellValue_Description {
            get {
                return ResourceManager.GetString("Table_GetCellValue_CellValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellValue.
        /// </summary>
        public static string Table_GetCellValue_CellValue_DisplayName {
            get {
                return ResourceManager.GetString("Table_GetCellValue_CellValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ex:5, Note: Index should start from 0.
        /// </summary>
        public static string Table_GetCellValue_ColumnIndex_Description {
            get {
                return ResourceManager.GetString("Table_GetCellValue_ColumnIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnIndex.
        /// </summary>
        public static string Table_GetCellValue_ColumnIndex_DisplayName {
            get {
                return ResourceManager.GetString("Table_GetCellValue_ColumnIndex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get table cell value.
        /// </summary>
        public static string Table_GetCellValue_Description {
            get {
                return ResourceManager.GetString("Table_GetCellValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table_GetCellValue.
        /// </summary>
        public static string Table_GetCellValue_DisplayName {
            get {
                return ResourceManager.GetString("Table_GetCellValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ex:5, Note: Index should start from 0.
        /// </summary>
        public static string Table_GetCellValue_RowIndex_Description {
            get {
                return ResourceManager.GetString("Table_GetCellValue_RowIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowIndex.
        /// </summary>
        public static string Table_GetCellValue_RowIndex_DisplayName {
            get {
                return ResourceManager.GetString("Table_GetCellValue_RowIndex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ex:&quot;wnd[0]/usr/tblSAPL&quot;.
        /// </summary>
        public static string Table_GetCellValue_TableID_Description {
            get {
                return ResourceManager.GetString("Table_GetCellValue_TableID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableID.
        /// </summary>
        public static string Table_GetCellValue_TableID_DisplayName {
            get {
                return ResourceManager.GetString("Table_GetCellValue_TableID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a row in a table.
        /// </summary>
        public static string TableRow_Select_Description {
            get {
                return ResourceManager.GetString("TableRow_Select_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableRow_Select.
        /// </summary>
        public static string TableRow_Select_DisplayName {
            get {
                return ResourceManager.GetString("TableRow_Select_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Example: &quot;6&quot;.
        /// </summary>
        public static string TableRow_Select_RowNumber_Description {
            get {
                return ResourceManager.GetString("TableRow_Select_RowNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowNumber.
        /// </summary>
        public static string TableRow_Select_RowNumber_DisplayName {
            get {
                return ResourceManager.GetString("TableRow_Select_RowNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;wnd[1]/usr/tblSAPLAQ_INT_FUNCTIONSTCH_FUNCAREAS&quot;.
        /// </summary>
        public static string TableRow_Select_TableID_Description {
            get {
                return ResourceManager.GetString("TableRow_Select_TableID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableID.
        /// </summary>
        public static string TableRow_Select_TableID_DisplayName {
            get {
                return ResourceManager.GetString("TableRow_Select_TableID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input TCode into SAP and start Transaction.
        /// </summary>
        public static string TCode_Input_Description {
            get {
                return ResourceManager.GetString("TCode_Input_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCode_Input.
        /// </summary>
        public static string TCode_Input_DisplayName {
            get {
                return ResourceManager.GetString("TCode_Input_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: &quot;ZVR019&quot;.
        /// </summary>
        public static string TCode_Input_TCODE_Description {
            get {
                return ResourceManager.GetString("TCode_Input_TCODE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCODE.
        /// </summary>
        public static string TCode_Input_TCODE_DisplayName {
            get {
                return ResourceManager.GetString("TCode_Input_TCODE_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: &quot;wnd[1]/usr/ctxtDY_FILENAME&quot;.
        /// </summary>
        public static string TextBox_Input_ControlID_Description {
            get {
                return ResourceManager.GetString("TextBox_Input_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string TextBox_Input_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("TextBox_Input_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input into Textbox.
        /// </summary>
        public static string TextBox_Input_Description {
            get {
                return ResourceManager.GetString("TextBox_Input_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox_Input.
        /// </summary>
        public static string TextBox_Input_DisplayName {
            get {
                return ResourceManager.GetString("TextBox_Input_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be Input, For example &quot;SampleText&quot;.
        /// </summary>
        public static string TextBox_Input_Text_Description {
            get {
                return ResourceManager.GetString("TextBox_Input_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextBox_Input_Text_DisplayName {
            get {
                return ResourceManager.GetString("TextBox_Input_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree control ID, for example:.
        /// </summary>
        public static string TreeItem_DoubleClick_ControlID_Description {
            get {
                return ResourceManager.GetString("TreeItem_DoubleClick_ControlID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlID.
        /// </summary>
        public static string TreeItem_DoubleClick_ControlID_DisplayName {
            get {
                return ResourceManager.GetString("TreeItem_DoubleClick_ControlID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click the Tree item/Node.
        /// </summary>
        public static string TreeItem_DoubleClick_Description {
            get {
                return ResourceManager.GetString("TreeItem_DoubleClick_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeItem_DoubleClick.
        /// </summary>
        public static string TreeItem_DoubleClick_DisplayName {
            get {
                return ResourceManager.GetString("TreeItem_DoubleClick_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key of the Tree Item/Node.
        /// </summary>
        public static string TreeItem_DoubleClick_ItemKey_Description {
            get {
                return ResourceManager.GetString("TreeItem_DoubleClick_ItemKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemKey.
        /// </summary>
        public static string TreeItem_DoubleClick_ItemKey_DisplayName {
            get {
                return ResourceManager.GetString("TreeItem_DoubleClick_ItemKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item in a Tree.
        /// </summary>
        public static string TreeView_Select_Description {
            get {
                return ResourceManager.GetString("TreeView_Select_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeView_Select.
        /// </summary>
        public static string TreeView_Select_DisplayName {
            get {
                return ResourceManager.GetString("TreeView_Select_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;wnd[0]/shellcont/shell/shellcont[0]/shell&quot;.
        /// </summary>
        public static string TreeView_Select_TreeID_Description {
            get {
                return ResourceManager.GetString("TreeView_Select_TreeID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeID.
        /// </summary>
        public static string TreeView_Select_TreeID_DisplayName {
            get {
                return ResourceManager.GetString("TreeView_Select_TreeID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Ex: &quot;000006&quot;.
        /// </summary>
        public static string TreeView_Select_TreeItemKey_Description {
            get {
                return ResourceManager.GetString("TreeView_Select_TreeItemKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeItemKey.
        /// </summary>
        public static string TreeView_Select_TreeItemKey_DisplayName {
            get {
                return ResourceManager.GetString("TreeView_Select_TreeItemKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
